# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ,"devCI" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x , 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: 依存関係のインストール(バックエンド)
      run: cd backend-ts && npm ci    
    - name: バックエンドのビルド
      run: cd backend-ts && npm run build --if-present
    - name: ユニットテスト(バックエンド)
      run: cd backend-ts && npm test
    
  Frontend-Ci:

    name: CI(フロントエンド)
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x , 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: 依存関係のインストール
        run: npm ci
      - name: ビルド
        run: npm run build --if-present
      - name: ユニットテスト
        run: npm test
