# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ,"devCI" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x , 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: 依存関係のインストール(バックエンド)
      run: cd backend-ts && npm ci    
    - name: 依存関係のインストール(フロントエンド)
      run: cd frontend && npm ci
    - name: フロントエンドのビルド
      run: cd frontend && npm run build --if-present
    - name: バックエンドのビルド
      run: cd backend-ts && npm run build --if-present
    - name: ユニットテスト(バックエンド)
      run: cd backend-ts && npm test
    - name: ユニットテスト(フロントエンド)
      run: cd frontend && npm test
